# Generated by Django 5.2.16 on 2026-07-25 05:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('height', models.FloatField(blank=True, help_text='Height in cm', null=True)),
                ('weight', models.FloatField(blank=True, help_text='Weight in kg', null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('blood_group', models.CharField(blank=True, max_length=5, null=True)),
                ('allergies', models.TextField(blank=True, null=True)),
                ('existing_conditions', models.TextField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('fitness_goal', models.CharField(blank=True, max_length=100, null=True)),
                ('water_goal', models.FloatField(default=2000, help_text='Water goal in ml')),
                ('sleep_goal', models.FloatField(default=8, help_text='Sleep goal in hours')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='health_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DailyWellness',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('water_intake', models.FloatField(default=0, help_text='Water intake in ml')),
                ('sleep_hours', models.FloatField(default=0)),
                ('exercise_duration', models.IntegerField(default=0, help_text='Exercise duration in minutes')),
                ('steps', models.IntegerField(default=0)),
                ('mood', models.CharField(blank=True, max_length=50, null=True)),
                ('stress_level', models.IntegerField(default=1)),
                ('heart_rate', models.IntegerField(blank=True, help_text='Heart rate in bpm', null=True)),
                ('blood_pressure', models.CharField(blank=True, help_text='e.g. 120/80', max_length=20, null=True)),
                ('blood_sugar', models.FloatField(blank=True, help_text='Blood sugar in mg/dL', null=True)),
                ('calories_consumed', models.IntegerField(default=0)),
                ('fruits_veg_servings', models.IntegerField(default=0)),
                ('screen_time', models.FloatField(default=0, help_text='Screen time in hours')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_wellness_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
