# Generated by Django 5.2.16 on 2026-07-25 05:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('prediction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease_name', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField()),
                ('causes', models.TextField(blank=True, null=True)),
                ('symptoms', models.JSONField(blank=True, default=list, help_text='List of typical symptoms')),
                ('precautions', models.JSONField(blank=True, default=list, help_text='List of precautions')),
                ('diet', models.JSONField(blank=True, default=dict, help_text="Dict with 'recommended' and 'avoid' lists")),
                ('home_remedies', models.JSONField(blank=True, default=list, help_text='List of home remedies')),
                ('specialist', models.CharField(help_text='Name of the specialist', max_length=255)),
            ],
            options={
                'db_table': 'diseases',
            },
        ),
        migrations.CreateModel(
            name='Specialist',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('specialist', models.CharField(max_length=255, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'specialists',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medicine_name', models.CharField(max_length=255)),
                ('medicine_type', models.CharField(default='OTC', max_length=100)),
                ('otc', models.BooleanField(default=True)),
                ('description', models.TextField()),
                ('precautions', models.TextField(blank=True, null=True)),
                ('disease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='recommendations.disease')),
            ],
            options={
                'db_table': 'medicines',
            },
        ),
        migrations.CreateModel(
            name='RecommendationHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('disease', models.CharField(max_length=255)),
                ('specialist', models.CharField(max_length=255)),
                ('viewed_at', models.DateTimeField(auto_now_add=True)),
                ('prediction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='prediction.predictionhistory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendation_histories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Recommendation Histories',
                'db_table': 'recommendation_history',
                'ordering': ['-viewed_at'],
            },
        ),
    ]
